### ISSUE TITLE
The Timeline resource is not saved when playing project

### ISSUE THREAD

**Issue by Crystalwarrior** [AnidemDex/Godot-EventSystem#23]
### OS

Occurred on Windows 10 x64 and Windows 11

### Godot Version

3.4.stable

### Plugin Version

1.2.1 (lastest)

### Issue description

If you press the "play project" or "play scene" buttons when editing the timeline without pressing Ctrl+S beforehand, that timeline resource will break for the rest of the editor session without telling you. It will appear as if the timeline is saved properly, but in-game tests indicate that is not the case. When reloading the project, it will be revealed that none of your changes actually saved.

It's a horrendously frustrating bug that should be fixed ASAP, it could be godot-related but regardless it must have something to do with the debug instance locking up the resources and perhaps the timeline resource does not save fast enough or something. Whatever it is it's utterly wack.

### Steps to reproduce

1. Create a timeline
2. Edit the timeline without saving via Ctrl+S
3. Launch your game.
4. Realize your in-game timeline does not match your most recent edits.
5. Restart the editor
6. Open the timeline
7. Realize your timeline did not save, despite lying to you saying it did.

### Workaround

Make a habit to Ctrl+S every time you edit the timeline for anything. Otherwise get used to reloading your project after every change :/

**Comment by mdsahiloss** [comment]
hey! you still need help in resolving this bug

**Comment by Crystalwarrior** [comment]
Here's the bug in action, the timeline resource is not modified even though the editor claims it is. I have it open in visual studio code and I edit it and it works.

https://user-images.githubusercontent.com/3470436/147822403-55bdb885-275d-4a9c-92df-cea688c24c06.mp4

**Comment by AnidemDex** [comment]
I think maybe something related to `save_external_data` but I'm not sure if it's a good idea to force it to save, verify if it's saved or simply remove that function. I'll keep debugging

**Comment by AnidemDex** [comment]
Related to https://github.com/Zylann/godot_heightmap_plugin/issues/101 (for future reference)

**Comment by Crystalwarrior** [comment]
Big problem, if you save a timeline that is like this, the save will not be recognized and you have to save at the "original" timeline (e.g. 1_present.tres)
So sub-resources require their main resource to be saved to update:
![image](https://user-images.githubusercontent.com/3470436/150587914-d15eff24-d4d1-4520-83cc-ff14e5f1a95b.png)

**Comment by AnidemDex** [comment]
Seems like https://github.com/AnidemDex/Godot-EventSystem/pull/44 solves it. If this can't be replicated anymore on main, I'll close the issue

**Comment by AnidemDex** [comment]
Can't replicate in 1.4.3
