### ISSUE TITLE
Add plugin to asset lib

### ISSUE THREAD

**Issue by jabsatz** [AnidemDex/Godot-EventSystem#3]
### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I was wondering if there was a particular reason this plugin is not in the [godot asset library](https://godotengine.org/asset-library/asset). It looks really promising and it could get more reach that way, while also being easier to add to projects from Godot directly

**Comment by AnidemDex** [comment]
There's no particular reason @jabsatz, is something planned, but I don't have an icon to upload it (is something required).

Gonna make some attemps and upload it

**Comment by AnidemDex** [comment]
Update: Made an icon, the plugin is pending for approval

**Comment by AnidemDex** [comment]
Update: The plugin is now in the asset library 🎉 ! Gonna update documentation.
https://godotengine.org/asset-library/asset/1119
