### ISSUE TITLE
`EventChangeTimeline`  add a way to come back to the original timeline

### ISSUE THREAD

**Issue by AnidemDex** [AnidemDex/Godot-EventSystem#32]
### Describe the feature / enhancement and how it helps to overcome the problem or limitation

`EventChangeTimeline` may be able to return to the caller timeline when the timeline ended. This way those two options are possible
```
|- Event A
|- Change Timeline (not return to original caller)
- Event B <- Not called
```
```
|- Event A
|- Change Timeline (return to original caller)
|- Event B <- Called when the previous timeline ends
```

**Comment by Crystalwarrior** [comment]
Do not have this as a "Change Timeline" option. Instead, add a new event for returning to previous timeline.
Call it a "return" or "go back" event, and rename this event to "end" or "end timeline" or "close dialog"
https://github.com/AnidemDex/Godot-EventSystem/issues/31

Otherwise this becomes an extension of the problem I mentioned with the Condition event in here https://github.com/AnidemDex/Godot-EventSystem/issues/34

**Comment by AnidemDex** [comment]
@Crystalwarrior events are isolated, they don't know about other events, so there's no way to tell the event how to return to a timeline used by other event

**Comment by Crystalwarrior** [comment]
@AnidemDex I understand for events but the timeline could have a method defined for returning to last TL, right? Or even the event manager as a whole. And the return event could simply call that function.

**Comment by AnidemDex** [comment]
@Crystalwarrior that method is contempled for `Sequence` resource. `Timeline`s are isolated as `Event` does, so they are not aware of other timelines or what its inner events does.

**Comment by Crystalwarrior** [comment]
> @Crystalwarrior that method is contempled for `Sequence` resource. `Timeline`s are isolated as `Event` does, so they are not aware of other timelines or what its inner events does.

I mean you could add a simple variable to a timeline that is a "return_timeline", and it's null by default, which decides what timeline is called when `return()` is called, and that return() func could be called by the event. The "return_timeline" could simply be a nodepath, with `return_event` being an event reference to return to? Something along these lines

**Comment by AnidemDex** [comment]
`Go To` event works for this purpose.
