### ISSUE TITLE
Event editor desyncs when using check boxes for if/else blocks

### ISSUE THREAD

**Issue by IcedQuinn** [AnidemDex/Godot-EventSystem#59]
### Godot Version

3.4.stable

### Plugin Version

1.4.1 (latest)

### Issue description

Creating a timeline for an if/else block then disabling it with the tick and creating a new timeline will result in the GUI becoming cursed and out of sync.

### Steps to reproduce

1. Create an if/else node
2. Create a new timeline for true
3. Place nodes in the branch
4. Uncheck events if
5. Create a new timeline for true
6. Despair

![2022-04-30_00-28](https://user-images.githubusercontent.com/70673392/166092716-f18b50bf-1ca6-4a03-86bd-ec19d9318b36.png)
![2022-04-30_00-28_1](https://user-images.githubusercontent.com/70673392/166092717-eb0554cc-2fe2-4349-a1c6-8de4eee31832.png)

**Comment by AnidemDex** [comment]
Thank you for the report. Probably is something related to the event not reporting the change to the editor. I'll investigate

**Comment by AnidemDex** [comment]
Seems like, with the refactor of the timeline editor in #62 this issue is no more. Feel free to open this issue again if you find it again.
