### ISSUE TITLE
"New" timeline buttons show all classes

### ISSUE THREAD

**Issue by IcedQuinn** [AnidemDex/Godot-EventSystem#60]
### Godot Version

3.4.stable

### Plugin Version

1.4.1 (latest)

### Issue description

Creating a new timeline doesn't seem to filter for the Timeline class; nor is there a way to save a timeline to an external file like there are in other parts of the Godot UI where this same UX is used.

### Steps to reproduce

1. Create an EventManager
2. Click on "Timeline"
3. Be flooded with "New $kitchen-sink" menu entries
![2022-04-30_00-33](https://user-images.githubusercontent.com/70673392/166092855-407a98bd-45ca-4a09-a2c9-8a3abb7b705a.png)

**Comment by AnidemDex** [comment]
Yes, is an annoying issue. I'm thinking on replace it with a custom picker.

The issue is related to https://github.com/godotengine/godot-proposals/issues/18

**Comment by AnidemDex** [comment]
#62 now has a custom editor that makes easy the creation of new timelines
