### ISSUE TITLE
"Go To" events show bizzare labels

### ISSUE THREAD

**Issue by IcedQuinn** [AnidemDex/Godot-EventSystem#61]
### Godot Version

3.4.stable

### Plugin Version

1.4.1 (latest)

### Issue description

Event shows an offset in to the timeline. This offset also does not update when the relevant target is moved nor are the numbers shown on the interface anywhere. It is possible to name an event such as a comment to work as a kind of movable label however the GUI shows the original offset instead of the block's name.

### Steps to reproduce

1. Create a comment
2. Rename the comment
3. Create a `go to` block
4. Set the target to the comment
5. Title will read "[0;]" instead of the comment block's name
![2022-04-30_00-36](https://user-images.githubusercontent.com/70673392/166092997-750e8bdf-894d-4cf6-a468-1ca4aa84f08b.png)

**Comment by AnidemDex** [comment]
All events uses the information saved in the event. In case of go to events, they uses an special string instead of the event information.

Yeah, is not clear at all, adding the information of the pointed event would be better

**Comment by AnidemDex** [comment]
Hey, this custom selector was added recently, what do you think?
![selector](https://user-images.githubusercontent.com/7025991/181687582-5fd92b19-2c83-4c4d-8ce2-839415f366f6.png)
